###服务端口号
server:
  port: 9100

###服务名称
spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enable: true #基于HTTP basic的认证
    user: #配置用户账号信息
      name: gxl
      password: 123456

eureka:
  instance:
    #注册中心地址
    hostname: 127.0.0.1

  ###客户端调用地址
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/
    ###是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）
    register-with-eureka: true
    ###是否从Eureka中获取注册信息,因为自己为注册中心,不会在该应用中的检索服务信息
    fetch-registry: true

  ###测试环境、开发环境可以关闭自我保护机制，保证服务不可用时及时剔除
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
