###服务端口号(本身是一个web项目)
server:
  port: 8081
###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如商品服务)
spring:
  application:
    name: app-item
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://gxl:123456@127.0.0.1:8100/eureka, http://gxl:123456@127.0.0.1:9100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实例id
